### ISSUE TITLE
Current version is broken

### ISSUE THREAD

**Issue by tsammut** [amiller27/OverviewAllWindows#10]
Hi! I love this extension; thanks for creating it!

It appears the current version of this extension does not work however, at least not with GNOME 3.20.0. Installing from extensions.gnome.org fails with an error, and installing the current version from github installs successfully, but fails to show all windows in the overview.

Installing the github version prior to https://github.com/amiller27/OverviewAllWindows/commit/8932510c137943ac2aeb21b6ef7266fe3fe0f23f works as expected.

**Comment by AntiNSA** [comment]
yep : (

**Comment by bittner** [comment]
The extension is still broken. An error shows both at time of installation and when you try to fire up the extension's settings page (e.g. in Gnome Tweaks app > Extensions).

Stack Trace
----------
```JavaScript
GLib.FileError: Failed to open file “/home/peter/.local/share/gnome-shell/extensions/OverviewAllWindows@amiller27/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  init@/home/peter/.local/share/gnome-shell/extensions/OverviewAllWindows@amiller27/prefs.js:15:22
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  ```

### Version Information

This refers to the current extension **version 8**, shell version **3.28.0** on Ubuntu 18.04 LTS (development branch), but I've seen other users report the same for other environments and yet older versions of the extension.

Troubleshooting
-----------

It looks like simply the subdirectory `schemas` is missing and should be packed into the installable extension. When you add that folder in `~/.local/share/gnome-shell/extensions/OverviewAllWindows@amiller27/` the extension starts working:

```bash
$ cd ~/.local/share/gnome-shell/extensions/OverviewAllWindows@amiller27/
$ mkdir schemas && ch schemas
$ wget -q https://raw.githubusercontent.com/amiller27/OverviewAllWindows/master/schemas/gschemas.compiled
$ wget -q https://raw.githubusercontent.com/amiller27/OverviewAllWindows/master/schemas/org.gnome.shell.extensions.overview-all-windows.gschema.xml
```

**Comment by bittner** [comment]
Who can repackage this extension also adding the `schemas` folder, so that it installs successfully?

**Comment by bittner** [comment]
IIUC it's all a matter of zipping the repo root folder up including the subdirectory, and then you @amiller27 have to upload it. We can't really change a configuration file or so (and make a PR) to fix this problem for the extension. Correct?

**Comment by amiller27** [comment]
I went and fixed everything.  Could you test installing a zipped version of the fix-prefs branch, and let me know if that works?  If it does I'll update the extension with those fixes.

**Comment by bittner** [comment]
@amiller27 Do you have any specific instructions for "installing a zipped version"? Just to make sure I actually do what you expect to verify the situation. (Sorry, I'm not sure.)

**Comment by amiller27** [comment]
You can get the zipfile from [here](https://github.com/amiller27/OverviewAllWindows/archive/fix-prefs.zip).  You then need to clean out the directory `~/.local/share/gnome-shell/extensions/OverviewAllWindows@amiller27`, and unzip the zipfile in there.  Then you should just be able to restart gnome-shell to reload the extension.

**Comment by bittner** [comment]
Seems to work fine.

**Comment by bittner** [comment]
The extension is still not installing from the [GNOME extensions website](https://extensions.gnome.org/extension/873/overview-all-windows/). Looks like your changes are not yet released. Can someone help to speed this up? I heard it has something to do with any extension needing a review.

**Comment by amiller27** [comment]
Yes, the update is waiting on a review.  Not sure if there's anything you can do to speed that up.
