### ISSUE TITLE
Keybinding for window switcher doesn't seem to work

### ISSUE THREAD

**Issue by bittner** [amiller27/OverviewAllWindows#13]
When I activate the extension setting "Replace overview? (Otherwise keybinding is <Super><Ctl>tab)" no change is apparent.

Expected Results
----------------

The enhanced overview showing thumbnails of all windows of all workspaces shows when I press `<Super>`+`<Tab>`.

Actual Results
---------

When I press `<Super>`+`<Tab>` only the usual, simple horizontal list of applications shows (same as when I press `<Alt>`+`<Tab>`).

Additional Comments
------

- It would be nice to have the regular overview with `<Alt>`+`<Tab>` and the enhanced overview with `<Super>`+`<Tab>`. Not sure if this would already be the case.
- Related: [pull request #8](https://github.com/amiller27/OverviewAllWindows/pull/8/files)

**Comment by bittner** [comment]
I'd like to prepare a PR to make `<Super>`+`<Tab>`, and optionally `<Shift>`+`<Super>` (if technically possible), display the unified overview aka Exposé. I have trouble understanding what to change in the code. I've specifically looked at the [keybinding functions](https://github.com/amiller27/OverviewAllWindows/blob/master/extension.js#L251-L267). Is this the right place?

Can anyone give a hint on how I should proceed? What would I have to change to make different keybindings work?

**Comment by amiller27** [comment]
I didn't personally write that part of the extension, so I'm not sure.  The keybinding stuff comes in from PR #8, so looking at the changes there might be a good place to start.  PR's are welcome, but I'm no longer doing development on this extension myself.

**Comment by bittner** [comment]
@Psykar Can you help? I'd like to map the unified overview to an alternative (the most intuitive?) button or keyboard shortcut. (Background: I'm struggling with `<Ctrl>`+`<Super>`+`<Tab>`. Maybe others do so, too.)

**Comment by Psykar** [comment]
Should be changeable with gconf-editor
path is `/org/gnome/shell/extensions/overview-all-windows/toggle-unified-overview`
Just change the binding there, and restart gnome.

**Comment by amiller27** [comment]
This seems resolved, I'm closing

**Comment by bittner** [comment]
@Psykar I don't have the path you mention in the GNOME registry. Is this maybe related to the failed installation? ([see screenshots](https://github.com/amiller27/OverviewAllWindows/issues/14#issuecomment-386667336))

Where can I find a list of possible key combinations, the official docs or so? (e.g. is `<Shift>`+`<Super>` possible to configure?)
