### ISSUE TITLE
Activate exposé (overview) with hot corner or hotkey

### ISSUE THREAD

**Issue by bittner** [amiller27/OverviewAllWindows#14]
It would be nice to have an exposé of all windows on all workspaces when I move the mouse to either the lower edge of the screen or the upper left corner, and optionally upon pressing some hotkey on the keyboard.

Not sure if this is already possible or even technically feasible with Gnome Shell. I recall this was possible with Unity.

**EDIT:** This was the [spread windows](http://4.bp.blogspot.com/-_4MdvYVP6WU/Uaz56O0pfFI/AAAAAAAAH4I/WEWWZr06SPs/s1600/unity-tweak-tool.png) function in the `unity-tweak-tool` back then.

**Comment by bittner** [comment]
Seems like this is _already_ exactly what this extension does! Only, that I manage to activate this feature via pressing `<Super>+<Tab>` only.

- Is there another way to activate the exposé/overview?
- How do I assign this feature to a hotcorner or the lower edge of the screen?

**Comment by bittner** [comment]
@Psykar Do you happen to know a solution also to this? Is there a way to attach a hot corner (or screen edge) to the Exposé feature?

**Comment by amiller27** [comment]
If you go into the extension settings in Gnome Tweak Tool and set it to replace the default overview (turn that switch to on), then the default overview hot corner will show all the windows, and pressing Super will also show all windows.  I'm not planning on implementing other hot corners, or the ability to have separate hot corners for the default overview and the one with all windows, but if you'd like to look into that and make a PR that would be great.

**Comment by bittner** [comment]
> then the default overview hot corner will show all the windows

Well, it doesn't. That's what confused me from the beginning. Both the hot corner and the `<Super>` key only show the windows of the current desktop, no matter whether you activate the "replace the default overview" option or not.

Some Additional Thoughts
-------------

Apart from making this feature work again (or make me understand what I do wrong) I think it would be handy to:

- make the "replace the default overview" option the default (as soon / as long as this extension is installed) - _in the end, this is somewhat the purpose of the extension, isn't it? I believe currently it's not selected by default._
- maybe re-word the "replace the default overview" option and add an explanatory text or screenshot, or
- maybe consider using two options instead of an on/off switch ("show all windows in overview (default)", "show windows of active desktop only (GNOME default)")

**Comment by bittner** [comment]
This here may be related to the problem. In `dconf-editor` I see the following:
![dconf-editor-replace-overview-no-schema](https://user-images.githubusercontent.com/665072/39641542-e3a37bea-4fce-11e8-8d68-b50be3633c6b.png)
![dconf-editor-replace-overview-no-schema-details](https://user-images.githubusercontent.com/665072/39641553-e9f18cee-4fce-11e8-9c6e-d49d7cd1b5e9.png)
This may be related to the fact that there was no `schema` directory available for the extension when it was installed; I added the folder (manually) with the content from GitHub after the installation to make the extension work.

**Comment by amiller27** [comment]
For your first comment:

The version currently on extensions.gnome.org is broken.

In the fixed version, which is currently awaiting review on extensions.gnome.org but can be installed right now from the repository here,
- The overview is replaced by default, and both `<Super>` and the top left hot corner should activate the overview with all windows
- Turning the switch to "off" in the preferences makes `<Super>` and the top left hot corner activate the normal overview, and makes `<Super>+<Ctrl>+<Tab>` activate the overview with all windows.

I'm not sure about changing the keybinding from `<Super>+<Ctrl>+<Tab>` in dconf, that does not work for me either.  If you want it to be changeable, please look at similar extensions with options for changing keybindings in their preferences, implement something similar, and make a PR here.

**Comment by amiller27** [comment]
For anyone still following this, the fixed version should now be available on extensions.gnome.org.

**Comment by bittner** [comment]
Works like a charm now, thanks! :1st_place_medal:
