### ISSUE TITLE
Not Working 3.36

### ISSUE THREAD

**Issue by jdaeira** [amiller27/OverviewAllWindows#17]
This extension is not working in Gnome 3.36. I'm a big fan of this extension. Do you plan to support?

**Comment by amiller27** [comment]
I do.  I've done some work on Gnome 3.36, the version currently on the gnome-336 branch of this repo is mostly working with some bugs that still need to be ironed out.  Not sure when I'll get that finished and up on extensions.gnome.org.

**Comment by amiller27** [comment]
I ended up having enough time to fix this tonight, master branch should work on 3.36 now, should be up on extensions.gnome.org soon.

**Comment by jdaeira** [comment]
That's awesome. Thank you so much for your hard work. Do you have a Patreon
ir anyway to contribute?

John da Eira

**Comment by amiller27** [comment]
Nope, thanks though.

**Comment by ferransabate** [comment]
Thanks a lot, these are great news!
