### ISSUE TITLE
Updating for Gnome 3.36 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ferransabate** [amiller27/OverviewAllWindows#19]
Hi, it would be possible to update the code to run with gnome 3.36 (Ubuntu 20,.04)? 

This is a great and useful extension which give a really useful function for those people that work with multiple workspaces.

I hope you will be able to do that.

Thanks a lot in advance.

**Comment by amiller27** [comment]
See #17

**Comment by ferransabate** [comment]
Thanks a lot!
