### ISSUE TITLE
Enhancement Request: Select Hotkey

### ISSUE THREAD

**Issue by tsammut** [amiller27/OverviewAllWindows#2]
Hi.

This is a great extension; thank you for creating it. 

Would it be possible to select the hotkey used to see the overview with all windows from all workspaces? It would be handy, for example, to press one key for regular overview and another for overview with all windows. 

Thanks!

**Comment by amiller27** [comment]
Hi Tim,
Thanks for the request.  It's not a trivial change, but I'll look into it and see what I can do.

**Comment by DanScharon** [comment]
That would be great! 
In addition I would prefer a different hot corner than the one for the regular overview (top left).

**Comment by Psykar** [comment]
It occurs to me that a *hacky* way to do this would be to have the hotkey re-setup the overview before triggering it, then reverting it again on close (basically do the enable extension steps before triggering the hotkey, and disabling it after the overview closes) Although I imagine this would have a potential to be very laggy.
