### ISSUE TITLE
fedora 25 and gnome 3.22 failure

### ISSUE THREAD

**Issue by baoboa** [amiller27/OverviewAllWindows#9]
did try to activate it and it show a error button, don't know if it's a compatibility problem with gnome 3.22

if  i try to access the setup menu i got that 

GLib.FileError: Failed to open file '/home/XXX/.local/share/gnome-shell/extensions/OverviewAllWindows@amiller27/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  init@/home/XXX/.local/share/gnome-shell/extensions/OverviewAllWindows@amiller27/prefs.js:15
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1

**Comment by bittner** [comment]
Duplicate of #10 (more generic report).

**Comment by baoboa** [comment]
ok
